#!/bin/sh

# If no project name is given
if [ $# -eq 0 ]
then

	# Display usage and stop
	echo "Usage: create <project.git>"
	exit 1

fi

# Set the project name, adding .git if necessary
project=$(echo "$*" | sed 's/\.git$\|$/.git/i')
repository="/home/git/repositories/$project"

# Create and initialise the project
mkdir "$repository" && \
cd "$repository" && \
git --bare init && \
ln -s "$repository" "/home/git/$project"
